allowBuilds:
  '@clerk/shared': true
  '@heroui/shared-utils': true
  '@parcel/watcher': false
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': true
  '@swc/core': false
  '@vercel/speed-insights': true
  core-js: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

overrides:
  '@types/react': 19.2.17
  '@types/react-dom': 19.2.3
