name: 🐛 Bug Report
description: Report a technical issue or unexpected behavior
title: '[BUG] '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        ### Before reporting
        - [ ] I've searched existing issues
        - [ ] I've checked documentation
        - [ ] I've updated to latest version

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        How to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected vs Actual Behavior
      description: What you expected to happen vs what actually happened
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        - OS: [e.g. Windows 11, macOS Sonoma]
        - Browser: [e.g. Chrome 122, Firefox 123]
        - Device: [e.g. Desktop, iPhone 15]
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Logs
      description: Add screenshots or error logs if applicable

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information about the problem